# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urban_auralization/ui/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 691)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(46, 49, 51);\n"
"    color: rgb(224, 224, 224);\n"
"}\n"
"\n"
"QWidget{\n"
"    color: rgb(224, 224, 224);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(58, 62, 70);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(82, 89, 103);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(151, 165, 191);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QStatusBar{\n"
"background-color: rgb(46, 49, 51);\n"
"}\n"
"\n"
"QGroupBox{\n"
"border-radius: 10px;\n"
"background-color: rgb(68, 79, 84);}\n"
"\n"
"QSlider{\n"
"background-color: rgb(68, 79, 84);\n"
"}\n"
"\n"
"QLineEdit{\n"
"padding-left:5px;\n"
"border-radius: 10px;\n"
"background-color: rgb(36, 44, 48);\n"
"}\n"
"\n"
"QListWidget{\n"
"padding-left:5px;\n"
"border-radius: 10px;\n"
"background-color: rgb(36, 44, 48);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 600, 721, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 20, 201, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 201, 291))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 171, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 91, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 121, 60, 16))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(10, 141, 181, 101))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 251, 31, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 251, 31, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 251, 101, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 30, 181, 32))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 380, 201, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(10, 110, 181, 22))
        self.horizontalSlider_3.setMaximum(360)
        self.horizontalSlider_3.setProperty("value", 90)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(10, 160, 181, 22))
        self.horizontalSlider_4.setMinimum(-90)
        self.horizontalSlider_4.setMaximum(90)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 85, 121, 21))
        self.label_4.setStyleSheet("background-color:transparent;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 136, 181, 20))
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 19, 171, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 50, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(240, 450, 501, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 90, 87, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 60, 121, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 87, 20))
        self.checkBox.setObjectName("checkBox")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(239, 20, 501, 381))
        self.widget.setStyleSheet("\n"
"border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 410, 31, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 410, 31, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(710, 410, 31, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(670, 410, 31, 32))
        self.pushButton_8.setObjectName("pushButton_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 36))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExport_as = QtWidgets.QAction(MainWindow)
        self.actionExport_as.setObjectName("actionExport_as")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_as)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Start simulation"))
        self.pushButton_2.setText(_translate("MainWindow", "Import geo model.stl"))
        self.groupBox.setTitle(_translate("MainWindow", "Source"))
        self.label_3.setText(_translate("MainWindow", "Velocity [m/s]"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "15"))
        self.label.setText(_translate("MainWindow", "Route"))
        self.pushButton_3.setText(_translate("MainWindow", "+"))
        self.pushButton_4.setText(_translate("MainWindow", "-"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "(0,0,0)"))
        self.pushButton_9.setText(_translate("MainWindow", "Import anechoic stimulus"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Receiver"))
        self.label_4.setText(_translate("MainWindow", "Azimuth"))
        self.label_5.setText(_translate("MainWindow", "Colatidude"))
        self.label_6.setText(_translate("MainWindow", "Position (x,y,z) [m]"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "(0,0,0)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Simulation"))
        self.checkBox_3.setText(_translate("MainWindow", "Wind"))
        self.checkBox_2.setText(_translate("MainWindow", "Doppler effect"))
        self.checkBox.setText(_translate("MainWindow", "Diffraction"))
        self.pushButton_5.setText(_translate("MainWindow", "Ø"))
        self.pushButton_6.setText(_translate("MainWindow", "Y"))
        self.pushButton_7.setText(_translate("MainWindow", "-"))
        self.pushButton_8.setText(_translate("MainWindow", "+"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExport_as.setText(_translate("MainWindow", "Export .wav..."))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
